### PR TITLE
Add client_max_body_size=200M in nginx configuration

### LINKED ISSUE #23: Correct PHP Upload Issues
There is a problem on Nginx configuration too, sometime when you upload a large file, the upload fails:

You need to fix nginx.conf at /etc/nginx/nginx.conf by adding this line inside http{ }:

client_max_body_size 20M;

### PR DESCRIPTION
**Pull request by moul**
Fix #23

### CODE REVIEW

**Comment by bnetter** [comment]
:+1:

**Comment by bnetter** [comment]
(much needed)

**Comment by bnetter** [comment]
capture d ecran 2015-11-16 a 14 32 38

**Comment by moul** [comment]
ping @edouardb

**Comment by edouardb** [comment]
LGTM

**Comment by moul** [comment]
The build is in progress: https://travis-ci.org/scaleway/qa/builds/91399668

**Pull request merged**
